In [3]:
import numpy as np
import pandas as pd
df_1 = pd.read_csv("Accident_Cities.csv")
#df_2 = pd.read_csv("Accident_States.csv")
print(df_1)
#print(df_2)

        Name of City  Total number of Fatal Accidents - 2011  \
0               Agra                                   336.0
1          Ahmedabad                                   222.0
2   Asansol-Durgapur                                   229.0
3         Aurangabad                                   161.0
4          Bengaluru                                   689.0
5             Bhopal                                   275.0
6         Coimbatore                                   253.0
7              Delhi                                  2007.0
8            Dhanbad                                    74.0
9          Faridabad                                   229.0
10         Ghaziabad                                   495.0
11           Gwalior                                   233.0
12         Hyderabad                                   428.0
13            Indore                                   407.0
14            Jaipur                                   387.0
15          Jabalpur                                   239.0
16        Jamshedpur                                   189.0
17           Jodhpur                                   236.0
18             Kochi                                   171.0
19           Kolkata                                   396.0
20            Kollam                                   209.0
21              Kota                                   102.0
22            Kannur                                    52.0
23           Lucknow                                   493.0
24          Ludhiana                                   260.0
25           Madurai                                   123.0
26        Mallapuram                                   290.0
27            Mumbai                                   539.0
28            Meerut                                   321.0
29            Nagpur                                   227.0
30             Patna                                   507.0
31              Pune                                    62.0
32            Rajkot                                   163.0
33             Surat                                   240.0
34          Srinagar                                     NaN
35          Thrissur                                   134.0
36           Vadodra                                   164.0
37          Varanasi                                    73.0
38     Visakhapatnam                                   410.0
39         Allahabad                                     NaN
40          Amritsar                                     NaN
41        Chandigarh                                     NaN
42           Chennai                                     NaN
43            Kanpur                                     NaN
44         Khozikode                                     NaN
45            Nashik                                     NaN
46            Raipur                                     NaN
47  Thiruvanthapuram                                     NaN
48    Tiruchirapalli                                     NaN
49    Vijaywada City                                     NaN
50             Vizaq                                     NaN

    All Accidents - 2011  Persons Killed - 2011  Persons Injured - 2011  \
0                 1299.0                  632.0                  1046.0
1                 2020.0                  227.0                  2036.0
2                  368.0                  230.0                   185.0
3                  719.0                  173.0                   744.0
4                 6031.0                  720.0                  4952.0
5                 3459.0                  299.0                  2970.0
6                 1126.0                  259.0                  1058.0
7                 7281.0                 2065.0                  7226.0
8                  138.0                   82.0                   106.0
9                  803.0                  249.0                   595.0
10                1109.0                  535.0                   817.0
11                2030.0                  248.0                  1626.0
12                2651.0                  441.0                  2528.0
13                4995.0                  425.0                  4053.0
14                2002.0                  406.0                  1915.0
15                2906.0                  260.0                  2990.0
16                 447.0                  207.0                   292.0
17                 526.0                  264.0                   525.0
18                1986.0                  182.0                  2008.0
19                3133.0                  418.0                  2420.0
20                1668.0                  222.0                  1811.0
21                 616.0                  113.0                   688.0
22                 557.0                   55.0                   833.0
23                1270.0                  517.0                   741.0
24                 444.0                  294.0                   189.0
25                 685.0                  125.0                   656.0
26                2694.0                  324.0                  3534.0
27               25471.0                  563.0                  5059.0
28                 886.0                  384.0                   679.0
29                1231.0                  236.0                  1144.0
30                1225.0                  507.0                   576.0
31                 261.0                   64.0                   213.0
32                1039.0                  172.0                  1042.0
33                1223.0                  248.0                   841.0
34                 492.0                   75.0                   511.0
35                1262.0                  141.0                  1343.0
36                1343.0                  172.0                   908.0
37                 142.0                   73.0                    69.0
38                1548.0                  414.0                  1286.0
39                   NaN                    NaN                     NaN
40                   NaN                    NaN                     NaN
41                   NaN                    NaN                     NaN
42                   NaN                    NaN                     NaN
43                   NaN                    NaN                     NaN
44                   NaN                    NaN                     NaN
45                   NaN                    NaN                     NaN
46                   NaN                    NaN                     NaN
47                   NaN                    NaN                     NaN
48                   NaN                    NaN                     NaN
49                   NaN                    NaN                     NaN
50                   NaN                    NaN                     NaN

    Total number of Fatal Accidents - 2012  All Accidents - 2012  \
0                                    381.0                 922.0
1                                    245.0                1850.0
2                                    199.0                 380.0
3                                    178.0                 715.0
4                                    707.0                5508.0
5                                    278.0                3623.0
6                                    263.0                1128.0
7                                   1822.0                6937.0
8                                     49.0                 144.0
9                                    227.0                 711.0
10                                   358.0                 850.0
11                                   213.0                1974.0
12                                   433.0                2577.0
13                                   419.0                5433.0
14                                   374.0                1792.0
15                                   251.0                2919.0
16                                   173.0                 424.0
17                                   313.0                 533.0
18                                   136.0                2280.0
19                                   471.0                3937.0
20                                   197.0                1763.0
21                                   108.0                 601.0
22                                    74.0                 618.0
23                                   474.0                1202.0
24                                   250.0                 430.0
25                                   121.0                 839.0
26                                   295.0                2711.0
27                                   471.0               24592.0
28                                   431.0                 964.0
29                                   273.0                1083.0
30                                   509.0                1185.0
31                                   388.0                1624.0
32                                   125.0                 981.0
33                                   225.0                1146.0
34                                    60.0                 511.0
35                                   119.0                1288.0
36                                   156.0                1196.0
37                                   216.0                 379.0
38                                     NaN                   NaN
39                                   396.0                 933.0
40                                    95.0                 152.0
41                                   130.0                 419.0
42                                  1367.0                9663.0
43                                   522.0                1257.0
44                                   166.0                1270.0
45                                   145.0                1023.0
46                                   348.0                2222.0
47                                   164.0                1933.0
48                                   139.0                 778.0
49                                   365.0                1600.0
50                                   371.0                1439.0

    Persons Killed - 2012  Persons Injured - 2012  Fatal Accidents - 2013  \
0                   427.0                   675.0                   436.0
1                   251.0                  1845.0                   227.0
2                   224.0                   315.0                   200.0
3                   192.0                   649.0                   150.0
4                   725.0                  4527.0                   733.0
5                   301.0                  3076.0                   242.0
6                   270.0                  1004.0                   245.0
7                  1866.0                  6633.0                  1778.0
8                    54.0                   191.0                   223.0
9                   247.0                   537.0                   205.0
10                  378.0                   710.0                   363.0
11                  232.0                  1434.0                   232.0
12                  464.0                  2471.0                   482.0
13                  447.0                  4419.0                   388.0
14                  391.0                  1636.0                   379.0
15                  275.0                  2545.0                   301.0
16                  189.0                   334.0                   147.0
17                  313.0                   436.0                   261.0
18                  144.0                  2431.0                   147.0
19                  498.0                  3216.0                   420.0
20                  213.0                  1909.0                   247.0
21                  112.0                   709.0                    98.0
22                   78.0                   814.0                    55.0
23                  497.0                   762.0                   458.0
24                  262.0                   250.0                   312.0
25                  127.0                   835.0                   140.0
26                  325.0                  3604.0                   314.0
27                  488.0                  4543.0                   481.0
28                  447.0                   833.0                   304.0
29                  280.0                   972.0                   298.0
30                  509.0                   556.0                   514.0
31                  407.0                  1392.0                   388.0
32                  151.0                   983.0                   115.0
33                  229.0                   867.0                   213.0
34                   64.0                   539.0                    59.0
35                  127.0                  1420.0                   127.0
36                  171.0                  1071.0                   175.0
37                  216.0                   160.0                   217.0
38                    NaN                     NaN                     NaN
39                  408.0                   573.0                   443.0
40                   95.0                    71.0                    92.0
41                  136.0                   347.0                   114.0
42                 1401.0                  8628.0                  1215.0
43                  564.0                   958.0                   472.0
44                  174.0                  1451.0                   172.0
45                  155.0                   461.0                   108.0
46                  362.0                  1558.0                   383.0
47                  167.0                  2244.0                   191.0
48                  142.0                   864.0                   121.0
49                  376.0                  1446.0                   320.0
50                  384.0                  1063.0                   382.0

         ...         Injured - 2014  Severity - 2014  Fatal Accidents - 2015  \
0        ...                  747.0             50.6                   498.0
1        ...                 1597.0             16.0                   318.0
2        ...                  284.0             47.4                   210.0
3        ...                  578.0             30.4                   153.0
4        ...                 4098.0             14.6                   708.0
5        ...                 2601.0              6.8                   222.0
6        ...                 1465.0             17.7                   238.0
7        ...                 8283.0             19.4                  1582.0
8        ...                   77.0             59.4                    42.0
9        ...                  466.0             36.0                   199.0
10       ...                  647.0             43.1                   316.0
11       ...                 1630.0             11.2                   249.0
12       ...                 2561.0             14.1                   425.0
13       ...                 4848.0              7.6                   421.0
14       ...                 1693.0             22.5                   452.0
15       ...                 3074.0             10.1                   345.0
16       ...                  163.0             38.7                   151.0
17       ...                  505.0             46.5                   257.0
18       ...                 2264.0              6.0                   159.0
19       ...                 3604.0              9.9                   412.0
20       ...                 1768.0             12.7                   191.0
21       ...                  771.0             16.3                   105.0
22       ...                  909.0             13.5                    65.0
23       ...                  838.0             39.6                   483.0
24       ...                  271.0             66.9                   260.0
25       ...                  643.0             14.6                   208.0
26       ...                 3305.0             13.1                   332.0
27       ...                 3938.0              2.4                   586.0
28       ...                  916.0             37.0                   372.0
29       ...                 1091.0             24.5                   254.0
30       ...                  682.0             41.3                   244.0
31       ...                 1402.0             25.4                   419.0
32       ...                  690.0             19.5                   136.0
33       ...                  817.0             27.4                   251.0
34       ...                  393.0             15.5                    59.0
35       ...                 1417.0              8.1                   103.0
36       ...                  990.0             18.7                   216.0
37       ...                  190.0             56.2                   200.0
38       ...                    NaN              NaN                     NaN
39       ...                  758.0             43.7                   455.0
40       ...                  125.0             57.0                    94.0
41       ...                  335.0             35.5                   124.0
42       ...                 9355.0             11.6                   859.0
43       ...                  941.0             48.0                   625.0
44       ...                 1253.0             13.5                   150.0
45       ...                  494.0             16.1                   225.0
46       ...                 1452.0             21.1                   406.0
47       ...                 2371.0              8.7                   159.0
48       ...                  766.0             25.3                   156.0
49       ...                 1578.0             20.1                   362.0
50       ...                 1356.0             21.9                   343.0

    Greviously Injured Accidents - 2015  Minor Accidents - 2015  \
0                                 369.0                   260.0
1                                 351.0                  1168.0
2                                 160.0                    60.0
3                                 297.0                   147.0
4                                1331.0                  1899.0
5                                 207.0                  2351.0
6                                 483.0                   664.0
7                                 372.0                  5971.0
8                                  48.0                    19.0
9                                  92.0                   374.0
10                                430.0                    70.0
11                                118.0                  1498.0
12                                484.0                  1635.0
13                                322.0                  4057.0
14                                758.0                   428.0
15                                370.0                  2287.0
16                                133.0                    38.0
17                                 70.0                   308.0
18                               1555.0                   560.0
19                               1357.0                  1404.0
20                               1233.0                   101.0
21                                180.0                   391.0
22                                262.0                   259.0
23                                379.0                   353.0
24                                133.0                    80.0
25                                 15.0                   768.0
26                               1923.0                   347.0

In [4]:
df_1.head()

,Name of City,Total number of Fatal Accidents - 2011,All Accidents - 2011,Persons Killed - 2011,Persons Injured - 2011,Total number of Fatal Accidents - 2012,All Accidents - 2012,Persons Killed - 2012,Persons Injured - 2012,Fatal Accidents - 2013,...,Injured - 2014,Severity - 2014,Fatal Accidents - 2015,Greviously Injured Accidents - 2015,Minor Accidents - 2015,Non-Injurey Accidents - 2015,Total Accidents - 2015,Killed - 2015,Injured - 2015,Severity - 2015
0,Agra,336.0,1299.0,632.0,1046.0,381.0,922.0,427.0,675.0,436.0,...,747.0,50.6,498.0,369.0,260.0,16.0,1143.0,474.0,650.0,41.5
1,Ahmedabad,222.0,2020.0,227.0,2036.0,245.0,1850.0,251.0,1845.0,227.0,...,1597.0,16.0,318.0,351.0,1168.0,0.0,1837.0,328.0,1722.0,17.9
2,Asansol-Durgapur,229.0,368.0,230.0,185.0,199.0,380.0,224.0,315.0,200.0,...,284.0,47.4,210.0,160.0,60.0,16.0,446.0,210.0,220.0,47.1
3,Aurangabad,161.0,719.0,173.0,744.0,178.0,715.0,192.0,649.0,150.0,...,578.0,30.4,153.0,297.0,147.0,57.0,654.0,170.0,670.0,26.0
4,Bengaluru,689.0,6031.0,720.0,4952.0,707.0,5508.0,725.0,4527.0,733.0,...,4098.0,14.6,708.0,1331.0,1899.0,896.0,4834.0,713.0,4057.0,14.7

In [8]:
df_1['Name of City']

0                 Agra
1            Ahmedabad
2     Asansol-Durgapur
3           Aurangabad
4            Bengaluru
5               Bhopal
6           Coimbatore
7                Delhi
8              Dhanbad
9            Faridabad
10           Ghaziabad
11             Gwalior
12           Hyderabad
13              Indore
14              Jaipur
15            Jabalpur
16          Jamshedpur
17             Jodhpur
18               Kochi
19             Kolkata
20              Kollam
21                Kota
22              Kannur
23             Lucknow
24            Ludhiana
25             Madurai
26          Mallapuram
27              Mumbai
28              Meerut
29              Nagpur
30               Patna
31                Pune
32              Rajkot
33               Surat
34            Srinagar
35            Thrissur
36             Vadodra
37            Varanasi
38       Visakhapatnam
39           Allahabad
40            Amritsar
41          Chandigarh
42             Chennai
43              Kanpur
44           Khozikode
45              Nashik
46              Raipur
47    Thiruvanthapuram
48      Tiruchirapalli
49      Vijaywada City
50               Vizaq
Name: Name of City, dtype: object

In [15]:
print(df_1[['Persons Injured-2011','Persons Injured-2012','Persons Injured-2013','Persons Injured-2014','Persons Injured-2015']].max())

KeyError: "['Persons Injured-2011' 'Persons Injured-2012' 'Persons Injured-2013'\n 'Persons Injured-2014' 'Persons Injured-2015'] not in index"

In [38]:
df_1.loc[1:2,::4].max()

Name of City              Asansol-Durgapur
Persons Injured - 2011                2036
Persons Injured - 2012                1845
Injured - 2013                        1855
Minor Accidents - 2014                1123
Injured - 2014                        1597
Minor Accidents - 2015                1168
Injured - 2015                        1722
dtype: object

In [18]:
df_1

,Name of City,Total number of Fatal Accidents - 2011,All Accidents - 2011,Persons Killed - 2011,Persons Injured - 2011,Total number of Fatal Accidents - 2012,All Accidents - 2012,Persons Killed - 2012,Persons Injured - 2012,Fatal Accidents - 2013,...,Injured - 2014,Severity - 2014,Fatal Accidents - 2015,Greviously Injured Accidents - 2015,Minor Accidents - 2015,Non-Injurey Accidents - 2015,Total Accidents - 2015,Killed - 2015,Injured - 2015,Severity - 2015
0,Agra,336.0,1299.0,632.0,1046.0,381.0,922.0,427.0,675.0,436.0,...,747.0,50.6,498.0,369.0,260.0,16.0,1143.0,474.0,650.0,41.5
1,Ahmedabad,222.0,2020.0,227.0,2036.0,245.0,1850.0,251.0,1845.0,227.0,...,1597.0,16.0,318.0,351.0,1168.0,0.0,1837.0,328.0,1722.0,17.9
2,Asansol-Durgapur,229.0,368.0,230.0,185.0,199.0,380.0,224.0,315.0,200.0,...,284.0,47.4,210.0,160.0,60.0,16.0,446.0,210.0,220.0,47.1
3,Aurangabad,161.0,719.0,173.0,744.0,178.0,715.0,192.0,649.0,150.0,...,578.0,30.4,153.0,297.0,147.0,57.0,654.0,170.0,670.0,26.0
4,Bengaluru,689.0,6031.0,720.0,4952.0,707.0,5508.0,725.0,4527.0,733.0,...,4098.0,14.6,708.0,1331.0,1899.0,896.0,4834.0,713.0,4057.0,14.7
5,Bhopal,275.0,3459.0,299.0,2970.0,278.0,3623.0,301.0,3076.0,242.0,...,2601.0,6.8,222.0,207.0,2351.0,841.0,3621.0,235.0,2779.0,6.5
6,Coimbatore,253.0,1126.0,259.0,1058.0,263.0,1128.0,270.0,1004.0,245.0,...,1465.0,17.7,238.0,483.0,664.0,128.0,1513.0,245.0,1393.0,16.2
7,Delhi,2007.0,7281.0,2065.0,7226.0,1822.0,6937.0,1866.0,6633.0,1778.0,...,8283.0,19.4,1582.0,372.0,5971.0,160.0,8085.0,1622.0,8258.0,20.1
8,Dhanbad,74.0,138.0,82.0,106.0,49.0,144.0,54.0,191.0,223.0,...,77.0,59.4,42.0,48.0,19.0,5.0,114.0,48.0,137.0,42.1
9,Faridabad,229.0,803.0,249.0,595.0,227.0,711.0,247.0,537.0,205.0,...,466.0,36.0,199.0,92.0,374.0,4.0,669.0,206.0,539.0,30.8
10,Ghaziabad,495.0,1109.0,535.0,817.0,358.0,850.0,378.0,710.0,363.0,...,647.0,43.1,316.0,430.0,70.0,10.0,826.0,331.0,668.0,40.1
11,Gwalior,233.0,2030.0,248.0,1626.0,213.0,1974.0,232.0,1434.0,232.0,...,1630.0,11.2,249.0,118.0,1498.0,275.0,2140.0,265.0,1703.0,12.4
12,Hyderabad,428.0,2651.0,441.0,2528.0,433.0,2577.0,464.0,2471.0,482.0,...,2561.0,14.1,425.0,484.0,1635.0,217.0,2761.0,425.0,2382.0,15.4
13,Indore,407.0,4995.0,425.0,4053.0,419.0,5433.0,447.0,4419.0,388.0,...,4848.0,7.6,421.0,322.0,4057.0,1073.0,5873.0,444.0,4685.0,7.6
14,Jaipur,387.0,2002.0,406.0,1915.0,374.0,1792.0,391.0,1636.0,379.0,...,1693.0,22.5,452.0,758.0,428.0,256.0,1894.0,476.0,1661.0,25.1
15,Jabalpur,239.0,2906.0,260.0,2990.0,251.0,2919.0,275.0,2545.0,301.0,...,3074.0,10.1,345.0,370.0,2287.0,372.0,3374.0,365.0,3216.0,10.8
16,Jamshedpur,189.0,447.0,207.0,292.0,173.0,424.0,189.0,334.0,147.0,...,163.0,38.7,151.0,133.0,38.0,25.0,347.0,157.0,329.0,45.2
17,Jodhpur,236.0,526.0,264.0,525.0,313.0,533.0,313.0,436.0,261.0,...,505.0,46.5,257.0,70.0,308.0,43.0,678.0,297.0,700.0,43.8
18,Kochi,171.0,1986.0,182.0,2008.0,136.0,2280.0,144.0,2431.0,147.0,...,2264.0,6.0,159.0,1555.0,560.0,287.0,2561.0,168.0,2721.0,6.6
19,Kolkata,396.0,3133.0,418.0,2420.0,471.0,3937.0,498.0,3216.0,420.0,...,3604.0,9.9,412.0,1357.0,1404.0,1174.0,4347.0,422.0,3329.0,9.7
20,Kollam,209.0,1668.0,222.0,1811.0,197.0,1763.0,213.0,1909.0,247.0,...,1768.0,12.7,191.0,1233.0,101.0,36.0,1561.0,204.0,1601.0,13.1
21,Kota,102.0,616.0,113.0,688.0,108.0,601.0,112.0,709.0,98.0,...,771.0,16.3,105.0,180.0,391.0,69.0,745.0,108.0,713.0,14.5
22,Kannur,52.0,557.0,55.0,833.0,74.0,618.0,78.0,814.0,55.0,...,909.0,13.5,65.0,262.0,259.0,38.0,624.0,67.0,796.0,10.7
23,Lucknow,493.0,1270.0,517.0,741.0,474.0,1202.0,497.0,762.0,458.0,...,838.0,39.6,483.0,379.0,353.0,156.0,1371.0,526.0,820.0,38.4
24,Ludhiana,260.0,444.0,294.0,189.0,250.0,430.0,262.0,250.0,312.0,...,271.0,66.9,260.0,133.0,80.0,16.0,489.0,271.0,324.0,55.4
25,Madurai,123.0,685.0,125.0,656.0,121.0,839.0,127.0,835.0,140.0,...,643.0,14.6,208.0,15.0,768.0,46.0,1037.0,215.0,1021.0,20.7
26,Mallapuram,290.0,2694.0,324.0,3534.0,295.0,2711.0,325.0,3604.0,314.0,...,3305.0,13.1,332.0,1923.0,347.0,280.0,2882.0,367.0,3264.0,12.7
27,Mumbai,539.0,25471.0,563.0,5059.0,471.0,24592.0,488.0,4543.0,481.0,...,3938.0,2.4,586.0,2034.0,1213.0,19635.0,23468.0,611.0,4029.0,2.6
28,Meerut,321.0,886.0,384.0,679.0,431.0,964.0,447.0,833.0,304.0,...,916.0,37.0,372.0,545.0,45.0,0.0,962.0,396.0,721.0,41.2
29,Nagpur,227.0,1231.0,236.0,1144.0,273.0,1083.0,280.0,972.0,298.0,...,1091.0,24.5,254.0,497.0,460.0,43.0,1254.0,260.0,1233.0,20.7
30,Patna,507.0,1225.0,507.0,576.0,509.0,1185.0,509.0,556.0,514.0,...,682.0,41.3,244.0,270.0,59.0,92.0,665.0,261.0,390.0,39.2
31,Pune,62.0,261.0,64.0,213.0,388.0,1624.0,407.0,1392.0,388.0,...,1402.0,25.4,419.0,568.0,367.0,89.0,1443.0,438.0,1205.0,30.4
32,Rajkot,163.0,1039.0,172.0,1042.0,125.0,981.0,151.0,983.0,115.0,...,690.0,19.5,136.0,134.0,432.0,78.0,780.0,150.0,716.0,19.2
33,Surat,240.0,1223.0,248.0,841.0,225.0,1146.0,229.0,867.0,213.0,...,817.0,27.4,251.0,386.0,179.0,87.0,903.0,257.0,773.0,28.5
34,Srinagar,NaN,492.0,75.0,511.0,60.0,511.0,64.0,539.0,59.0,...,393.0,15.5,59.0,1.0,336.0,39.0,435.0,63.0,462.0,14.5
35,Thrissur,134.0,1262.0,141.0,1343.0,119.0,1288.0,127.0,1420.0,127.0,...,1417.0,8.1,103.0,870.0,319.0,114.0,1406.0,110.0,1538.0,7.8
36,Vadodra,164.0,1343.0,172.0,908.0,156.0,1196.0,171.0,1071.0,175.0,...,990.0,18.7,216.0,387.0,332.0,229.0,1164.0,229.0,984.0,19.7
37,Varanasi,73.0,142.0,73.0,69.0,216.0,379.0,216.0,160.0,217.0,...,190.0,56.2,200.0,171.0,51.0,2.0,424.0,203.0,225.0,47.9
38,Visakhapatnam,410.0,1548.0,414.0,1286.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Allahabad,NaN,NaN,NaN,NaN,396.0,933.0,408.0,573.0,443.0,...,758.0,43.7,455.0,389.0,159.0,16.0,1019.0,479.0,698.0,47.0
40,Amritsar,NaN,NaN,NaN,NaN,95.0,152.0,95.0,71.0,92.0,...,125.0,57.0,94.0,37.0,16.0,3.0,150.0,99.0,89.0,66.0
41,Chandigarh,NaN,NaN,NaN,NaN,130.0,419.0,136.0,347.0,114.0,...,335.0,35.5,124.0,7.0,236.0,49.0,416.0,129.0,331.0,31.0
42,Chennai,NaN,NaN,NaN,NaN,1367.0,9663.0,1401.0,8628.0,1215.0,...,9355.0,11.6,859.0,2949.0,3196.0,324.0,7328.0,886.0,7320.0,12.1
43,Kanpur,NaN,NaN,NaN,NaN,522.0,1257.0,564.0,958.0,472.0,...,941.0,48.0,625.0,185.0,686.0,0.0,1496.0,665.0,1077.0,44.5
44,Khozikode,NaN,NaN,NaN,NaN,166.0,1270.0,174.0,1451.0,172.0,...,1253.0,13.5,150.0,931.0,247.0,159.0,1487.0,159.0,1567.0,10.7
45,Nashik,NaN,NaN,NaN,NaN,145.0,1023.0,155.0,461.0,108.0,...,494.0,16.1,225.0,309.0,181.0,586.0,1301.0,234.0,679.0,18.0
46,Raipur,NaN,NaN,NaN,NaN,348.0,2222.0,362.0,1558.0,383.0,...,1452.0,21.1,406.0,106.0,1048.0,629.0,2189.0,448.0,1431.0,20.5
47,Thiruvanthapuram,NaN,NaN,NaN,NaN,164.0,1933.0,167.0,2244.0,191.0,...,2371.0,8.7,159.0,1626.0,316.0,98.0,2199.0,164.0,2660.0,7.5
48,Tiruchirapalli,NaN,NaN,NaN,NaN,139.0,778.0,142.0,864.0,121.0,...,766.0,25.3,156.0,7.0,597.0,68.0,828.0,161.0,873.0,19.4
49,Vijaywada City,NaN,NaN,NaN,NaN,365.0,1600.0,376.0,1446.0,320.0,...,1578.0,20.1,362.0,335.0,850.0,97.0,1644.0,379.0,1548.0,23.1
50,Vizaq,NaN,NaN,NaN,NaN,371.0,1439.0,384.0,1063.0,382.0,...,1356.0,21.9,343.0,771.0,186.0,337.0,1637.0,373.0,1313.0,22.8

In [46]:
df_1['Name of City'] = df_1[[                ]].max()

In [48]:
df_3

Persons Injured - 2011    7226.0
Persons Injured - 2012    8628.0
Injured - 2013            8700.0
Injured - 2014            9355.0
Injured - 2015            8258.0
dtype: float64

In [50]:
df_1 = pd.DataFrame(df_1,columns=['Name of City','Persons Injured - 2011','Persons Injured - 2012','Injured - 2013','Injured - 2014','Injured - 2015'])
df_1

,Name of City,Persons Injured - 2011,Persons Injured - 2012,Injured - 2013,Injured - 2014,Injured - 2015
0,NaN,1046.0,675.0,750.0,747.0,650.0
1,NaN,2036.0,1845.0,1855.0,1597.0,1722.0
2,NaN,185.0,315.0,404.0,284.0,220.0
3,NaN,744.0,649.0,547.0,578.0,670.0
4,NaN,4952.0,4527.0,4334.0,4098.0,4057.0
5,NaN,2970.0,3076.0,2615.0,2601.0,2779.0
6,NaN,1058.0,1004.0,1138.0,1465.0,1393.0
7,NaN,7226.0,6633.0,7098.0,8283.0,8258.0
8,NaN,106.0,191.0,551.0,77.0,137.0
9,NaN,595.0,537.0,507.0,466.0,539.0
10,NaN,817.0,710.0,667.0,647.0,668.0
11,NaN,1626.0,1434.0,1470.0,1630.0,1703.0
12,NaN,2528.0,2471.0,2237.0,2561.0,2382.0
13,NaN,4053.0,4419.0,4407.0,4848.0,4685.0
14,NaN,1915.0,1636.0,1525.0,1693.0,1661.0
15,NaN,2990.0,2545.0,2639.0,3074.0,3216.0
16,NaN,292.0,334.0,384.0,163.0,329.0
17,NaN,525.0,436.0,536.0,505.0,700.0
18,NaN,2008.0,2431.0,2219.0,2264.0,2721.0
19,NaN,2420.0,3216.0,3577.0,3604.0,3329.0
20,NaN,1811.0,1909.0,1659.0,1768.0,1601.0
21,NaN,688.0,709.0,784.0,771.0,713.0
22,NaN,833.0,814.0,737.0,909.0,796.0
23,NaN,741.0,762.0,762.0,838.0,820.0
24,NaN,189.0,250.0,291.0,271.0,324.0
25,NaN,656.0,835.0,668.0,643.0,1021.0
26,NaN,3534.0,3604.0,3249.0,3305.0,3264.0
27,NaN,5059.0,4543.0,4250.0,3938.0,4029.0
28,NaN,679.0,833.0,774.0,916.0,721.0
29,NaN,1144.0,972.0,1237.0,1091.0,1233.0
30,NaN,576.0,556.0,567.0,682.0,390.0
31,NaN,213.0,1392.0,1503.0,1402.0,1205.0
32,NaN,1042.0,983.0,761.0,690.0,716.0
33,NaN,841.0,867.0,740.0,817.0,773.0
34,NaN,511.0,539.0,477.0,393.0,462.0
35,NaN,1343.0,1420.0,1400.0,1417.0,1538.0
36,NaN,908.0,1071.0,1051.0,990.0,984.0
37,NaN,69.0,160.0,199.0,190.0,225.0
38,NaN,1286.0,NaN,NaN,NaN,NaN
39,NaN,NaN,573.0,813.0,758.0,698.0
40,NaN,NaN,71.0,76.0,125.0,89.0
41,NaN,NaN,347.0,335.0,335.0,331.0
42,NaN,NaN,8628.0,8700.0,9355.0,7320.0
43,NaN,NaN,958.0,923.0,941.0,1077.0
44,NaN,NaN,1451.0,1298.0,1253.0,1567.0
45,NaN,NaN,461.0,616.0,494.0,679.0
46,NaN,NaN,1558.0,1315.0,1452.0,1431.0
47,NaN,NaN,2244.0,2341.0,2371.0,2660.0
48,NaN,NaN,864.0,701.0,766.0,873.0
49,NaN,NaN,1446.0,1464.0,1578.0,1548.0
50,NaN,NaN,1063.0,1229.0,1356.0,1313.0

In [51]:
df_1['Name of City']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
43   NaN
44   NaN
45   NaN
46   NaN
47   NaN
48   NaN
49   NaN
50   NaN
Name: Name of City, dtype: float64